setwd('/Users/jiesun/Dropbox/PROJECT_JE/Comparing_WHOIG') #@@
library(ggplot2)
library(tidyr)

library(grid)
library(gridExtra)

# 1. Extract_Cases_Country.R =============================

# NOTE #
# Extract and compare cases between RF and WHO-IG
# ---- #

cat('===== START [Extract_Cases_Country.R] =====\n')

# # Get directory of the script (this part only work if source the code, wont work if run directly in the console)
# # This can be set manually !!!
# script.dir <- dirname(sys.frame(1)$ofile)
# script.dir <- paste0(script.dir, '/')
# setwd(script.dir)

# Create folder to store the result (will show warnings if the folder already exists --> but just warning, no problem)
setwd("C:/Users/shreya/Documents/nBox/JE Jie")
dir.create(file.path('XGB_Compare'), showWarnings = TRUE) #@@

LinkData <- '/Users/jiesun/Dropbox/PROJECT_JE/Generate_Cases/' # Data folder is from the Generate_Cases part #@@

Extract_Values_Country <- function(DF_Vals, DF_Coords, Index){
  # Extract values of entire map based on their countries
  # DF_Vals: Dataframe containing values in entire map
  # DF_Coords: Dataframe containing pixel's index indicating which country it belongs to
  # Index: Name of index in DF_Coords
  # Index + DF_Coords has to match
  # Coords in DF_Vals + DF_Coords have to match
  # @@ SJ: adjusted the condition as dx is extremely small (1.82e-12), maybe due to small rounding
  
  result <- vector('list', length(Index))
  names(result) <- Index
  # Check Coord match
  dx <- abs(DF_Vals$x - DF_Coords$x)
  dy <- abs(DF_Vals$y - DF_Coords$y)
  if (dx < 1.9e-12 && dy == 0){ #@@adjusted here 
    for (idx.country in 1 : length(Index)){
      idx_point <- which(DF_Coords[[3]] == idx.country)
      if (length(idx_point) > 0){
        vals <- DF_Vals[[3]][idx_point]
        result[[idx.country]] <- vals
      }
    }
  }else{
    cat('COORDINATES DO NOT MATCH --> STOP!!!\n')
  }
  return(result)
}

# Read data from generated cases dataframe (from Generate Cases part)
Link_Generate_Cases_DF <- paste0(LinkData, 'Generate/Cases/XGB/') #@@
ListFiles <- list.files(Link_Generate_Cases_DF) # Make sure that you have to run the Generate Cases part before run the Comparing part

##### Read Map data #####
setwd("C:/Users/shreya/Documents/nBox/JE Jie/")

Country_Index <- readRDS("Generate/Data/Country_Index.Rds") # index of countries
Coord_Regions_Final <- readRDS("Generate/Data/Coord_Regions_Final.Rds") # country index of each pixel
Cases.map <- readRDS("Generate/Data/Cases_TotalXGB.Rds") # Take total cases (index 101) #@@

Cases.map <- Extract_Values_Country(Cases.map, Coord_Regions_Final, Country_Index)
# Fix Low.NPL and High.NPL
Cases.map$NPL <- c(Cases.map$Low.NPL, Cases.map$High.NPL)
Cases.map$MAC <- NULL
Cases.map$Low.NPL <- NULL
Cases.map$High.NPL <- NULL
# Add HKG in CHN
Cases.map$CHN <- c(Cases.map$CHN, Cases.map$HKG)
Cases.map$HKG <- NULL
for (idx in 1 : length(Cases.map)){
  Cases.map[[idx]] <- sum(Cases.map[[idx]])
}

Cases.map.GB <- readRDS("Generate/Data/Cases_TotalGB.Rds")
Cases.map.GB <- Extract_Values_Country(Cases.map.GB, Coord_Regions_Final, Country_Index)
Cases.map.GB$NPL <- c(Cases.map.GB$Low.NPL, Cases.map.GB$High.NPL)
Cases.map.GB$MAC <- NULL
Cases.map.GB$Low.NPL <- NULL
Cases.map.GB$High.NPL <- NULL
# Add HKG in CHN
Cases.map.GB$CHN <- c(Cases.map.GB$CHN, Cases.map.GB$HKG)
Cases.map.GB$HKG <- NULL

for (idx in 1 : length(Cases.map.GB)){
  Cases.map.GB[[idx]] <- sum(Cases.map.GB[[idx]])
}
Cases.map.RF <- readRDS("Generate/Data/Cases_TotalRF.Rds")
Cases.map.RF <- Extract_Values_Country(Cases.map.RF, Coord_Regions_Final, Country_Index)

Cases.map.RF$NPL <- c(Cases.map.RF$Low.NPL, Cases.map.RF$High.NPL)
Cases.map.RF$MAC <- NULL
Cases.map.RF$Low.NPL <- NULL
Cases.map.RF$High.NPL <- NULL
# Add HKG in CHN
Cases.map.RF$CHN <- c(Cases.map.RF$CHN, Cases.map.RF$HKG)
Cases.map.RF$HKG <- NULL
# Sum cases in all pixels

for (idx in 1 : length(Cases.map.RF)){
  Cases.map.RF[[idx]] <- sum(Cases.map.RF[[idx]])
}



##### Read Modelling data #####
# Cases generated by Quan (WHO-IG)
Cases.mod <- readRDS("Generate/Data/no_vac_cases_gen_age_sum_or.rds") # year 1950 - 2015 --> 66 cols / 1600 rows --> 1600 FOI posteriors
for (i in 1 : length(Cases.mod)){
  Cases.mod[[i]] <- as.numeric(Cases.mod[[i]][,66])
}

# Adjust Low.CHN, High.CHN
Cases.mod$CHN <- Cases.mod$Low.CHN + Cases.mod$High.CHN
Cases.mod$Low.CHN <- NULL
Cases.mod$High.CHN <- NULL
# Adjust Low.IDN, High.IDN
Cases.mod$IDN <- Cases.mod$Low.IDN + Cases.mod$High.IDN
Cases.mod$Low.IDN <- NULL
Cases.mod$High.IDN <- NULL
# Adjust Low.IND, High.IND, Medium.IND
Cases.mod$IND <- Cases.mod$Low.IND + Cases.mod$Medium.IND + Cases.mod$High.IND
Cases.mod$Low.IND <- NULL
Cases.mod$High.IND <- NULL
Cases.mod$Medium.IND <- NULL
# Adjust Low.NPL, High.NPL
Cases.mod$NPL <- Cases.mod$Low.NPL + Cases.mod$High.NPL
Cases.mod$Low.NPL <- NULL
Cases.mod$High.NPL <- NULL
# Adjust total_TWN
names(Cases.mod)[which(names(Cases.mod) == 'total_TWN')] <- 'TWN'

# Mean cases in all elements (1600 FOIs --> 1600 results --> take means)
for (idx in 1 : length(Cases.mod)){
  Cases.mod[[idx]] <- mean(Cases.mod[[idx]])
}

##### Create DF Compare #####
Countries <- names(Cases.map)
df <- data.frame(country = Countries, mod = 0, map = 0)
df$country <- as.character(df$country)
for (idx in 1 : nrow(df)){
  country <- df$country[idx]
  df$map[idx] <- Cases.map[[which(names(Cases.map) == country)]]
  df$mod[idx] <- Cases.mod[[which(names(Cases.mod) == country)]]
}
df$map <- round(df$map)
df$mod <- round(df$mod)

# level_oiginal <- AUS BRN BTN RUS SGP TLS JPN LAO PRK PNG TWN LKA KHM PAK KOR MYS NPL THA MMR VNM PHL BGD IDN IND CHN
# lv <- c('AUS', 'BRN', 'BTN', 'TLS', 'RUS', 'SGP', 'LAO', 'PNG', 'KHM',
#         'LKA', 'PRK', 'TWN', 'NPL', 'MYS', 'PAK', 'KOR', 'MMR', 'THA', 'VNM',
#         'PHL', 'JPN', 'BGD', 'IDN', 'IND', 'CHN')
df$country <- factor(df$country, levels = unique(df$country[order(df$mod)]), ordered = TRUE) # order based on modelling values (WHO-IG)
# df$country <- factor(df$country, levels = lv, ordered = TRUE) # order based on mod values

df_long <- gather(df, method, cases, mod, map, factor_key = TRUE)
colnames(df_long) <- c('Country', 'Method', 'Cases')
df_long$Method <- as.character(df_long$Method)
df_long$Method[which(df_long$Method == 'mod')] <- 'WHO-IG'
df_long$Method[which(df_long$Method == 'map')] <- 'XGB'



Countries <- names(Cases.map)
df <- data.frame(country = Countries, mod = 0, map = 0)
df$country <- as.character(df$country)
df <- data.frame(country = Countries, mod = 0, map = 0)
df$country <- as.character(df$country)
for (idx in 1 : nrow(df)){
  country <- df$country[idx]
  df$map[idx] <- Cases.map.GB[[which(names(Cases.map.GB) == country)]]
  df$mod[idx] <- Cases.mod[[which(names(Cases.mod) == country)]]
}
df$map <- round(df$map)
df$mod <- round(df$mod)

# level_oiginal <- AUS BRN BTN RUS SGP TLS JPN LAO PRK PNG TWN LKA KHM PAK KOR MYS NPL THA MMR VNM PHL BGD IDN IND CHN
# lv <- c('AUS', 'BRN', 'BTN', 'TLS', 'RUS', 'SGP', 'LAO', 'PNG', 'KHM',
#         'LKA', 'PRK', 'TWN', 'NPL', 'MYS', 'PAK', 'KOR', 'MMR', 'THA', 'VNM',
#         'PHL', 'JPN', 'BGD', 'IDN', 'IND', 'CHN')
df$country <- factor(df$country, levels = unique(df$country[order(df$mod)]), ordered = TRUE) # order based on modelling values (WHO-IG)
# df$country <- factor(df$country, levels = lv, ordered = TRUE) # order based on mod values

df_long_GB <- gather(df, method, cases, mod, map, factor_key = TRUE)
colnames(df_long_GB) <- c('Country', 'Method', 'Cases')
df_long_GB$Method <- as.character(df_long_GB$Method)
df_long_GB$Method[which(df_long_GB$Method == 'mod')] <- 'WHO-IG'
df_long_GB$Method[which(df_long_GB$Method == 'map')] <- 'GB'


Countries <- names(Cases.map)
df <- data.frame(country = Countries, mod = 0, map = 0)
df$country <- as.character(df$country)
df <- data.frame(country = Countries, mod = 0, map = 0)
df$country <- as.character(df$country)
for (idx in 1 : nrow(df)){
  country <- df$country[idx]
  df$map[idx] <- Cases.map.GB[[which(names(Cases.map.RF) == country)]]
  df$mod[idx] <- Cases.mod[[which(names(Cases.mod) == country)]]
}
df$map <- round(df$map)
df$mod <- round(df$mod)

# level_oiginal <- AUS BRN BTN RUS SGP TLS JPN LAO PRK PNG TWN LKA KHM PAK KOR MYS NPL THA MMR VNM PHL BGD IDN IND CHN
# lv <- c('AUS', 'BRN', 'BTN', 'TLS', 'RUS', 'SGP', 'LAO', 'PNG', 'KHM',
#         'LKA', 'PRK', 'TWN', 'NPL', 'MYS', 'PAK', 'KOR', 'MMR', 'THA', 'VNM',
#         'PHL', 'JPN', 'BGD', 'IDN', 'IND', 'CHN')
df$country <- factor(df$country, levels = unique(df$country[order(df$mod)]), ordered = TRUE) # order based on modelling values (WHO-IG)
# df$country <- factor(df$country, levels = lv, ordered = TRUE) # order based on mod values

df_long_RF <- gather(df, method, cases, mod, map, factor_key = TRUE)
colnames(df_long_RF) <- c('Country', 'Method', 'Cases')
df_long_RF$Method <- as.character(df_long_RF$Method)
df_long_RF$Method[which(df_long_RF$Method == 'mod')] <- 'WHO-IG'
df_long_RF$Method[which(df_long_RF$Method == 'map')] <- 'RF'

df_long <- rbind(df_long, df_long_GB[26:50,], df_long_RF[26:50,])

##### SUBPLOT #####
# Divided Manually based on the cases --> divided into subgroup in order to make easier to see the plot (y-axis varies alot between countries)
part1 <- levels(df$country)[1 : 6]
part2 <- levels(df$country)[7 : 17]
part3 <- levels(df$country)[18 : 23]
part4 <- levels(df$country)[24 : 25]

df_long$Part <- 0
df_long$Part[which(df_long$Country %in% part1)] <- 1
df_long$Part[which(df_long$Country %in% part2)] <- 2
df_long$Part[which(df_long$Country %in% part3)] <- 3
df_long$Part[which(df_long$Country %in% part4)] <- 4
df_long$Method[1:25] <- "Quan et al."
df_long$Method <- factor(df_long$Method, levels = c("Quan et al.", "XGB", "GB", "RF"))
df_long$Cases[df_long$Cases < 0] = 0
color <- c("#43658B", "#ED6663", "#F6856B", "#FFA372" )
names(color) <- c('Quan et al.', 'XGB', 'GB', 'RF')
colscale <- scale_fill_manual(name = 'Method', values = color)

p <- ggplot(df_long, aes(x = Country, y = Cases, fill = Method)) + 
  geom_bar(stat = 'identity', position = position_dodge(), alpha = 0.75) + colscale
p <- p + facet_wrap(~Part, scale = 'free_y', ncol = 1)
p <- p + theme(axis.text.x = element_text(angle = 90), plot.title = element_text(hjust = 0.5))
p <- p + ggtitle('Comparing Cases- Modelling vs Quan et al.') +  xlab('Countries') + ylab('Cases') #@@
p

cat('===== FINISH [Extract_Cases_Country.R] =====\n')
# SAVE FILE
ggsave(filename = 'Case_Compare.png', width = 108*2.5, height = 72*2.5, units = 'mm', plot = p)

